Psifx text
psifx/psifx pull request #14
Opened 2024-12-03 14:36 UTC by M-Rochat

Rebased onto psifx-update

2025-01-09 14:06 UTC, matthewvowels1 requested changes
- revert docker username to psifx (not a private secret)
- remove hugging-face option from argument (only hf)
- revert to tar.gz

2025-01-14 12:04 UTC, matthewvowels1 submitted a review, later dismissed

2025-01-27 12:04 UTC, GuillaumeRochette approved these changes

2025-01-27 12:23 UTC, matthewvowels1 submitted a review, later dismissed

2025-01-28 10:27 UTC, matthewvowels1 approved these changes

2025-01-28 10:27 UTC, matthewvowels1 approved these changes

2025-01-28 15:54 UTC, matthewvowels1 approved these changes

2025-01-28 15:54 UTC, merged